//
// Created by aSUSS on 2018/6/21.
//

#ifndef SOFTWARECOURSEDESIGN_GRAMMARANALYSIS_H
#define SOFTWARECOURSEDESIGN_GRAMMARANALYSIS_H

#endif //SOFTWARECOURSEDESIGN_GRAMMARANALYSIS_H


int grammarAnalysisMain();
