//
// Created by aSUSS on 2018/6/21.
//

#ifndef SOFTWARECOURSEDESIGN_SEMANTICANALYSIS_H
#define SOFTWARECOURSEDESIGN_SEMANTICANALYSIS_H

#endif //SOFTWARECOURSEDESIGN_SEMANTICANALYSIS_H

int semanticAnalysisMain();